version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: pthongtaem/upload-test
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "3000:3000"
    networks:
      - webnet
    volumes:
       - db-data:/usr/src/app/uploads      
volumes:
  db-data:
networks:
  webnet:
